on:
  release:
    types:
      - published
  workflow_dispatch:

name: release

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: deps
        run: python -m pip install -U build
      - name: build
        run: python -m build
      - name: store packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
  pypi:
    name: upload release to TestPyPI
    runs-on: ubuntu-latest
    needs:
      - build
    environment:
      name: pypi
      url: https://test.pypi.org/p/nirahmq/
    permissions:
      id-token: write
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
